receivers:
  otlp:
    protocols:
      grpc:
      http:


exporters:
  logging:
    loglevel: debug



service:
  telemetry:
    logs:
      level: DEBUG
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]