apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: {{ .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-demo
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-demo
  template:
    metadata:
      labels:
        app: metrics-demo
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: metrics-demo
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          image: "{{ .Values.metrics.hub }}/{{ .Values.metrics.image }}:{{ .Values.metrics.tag }}"
          ports:
            - name: http-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: metrics-demo
